require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

pod 'Firebase/Core', '~> 6.8.1'
pod 'Firebase/Messaging', '~> 6.8.1'
pod 'Firebase/DynamicLinks', '~> 6.8.1'
pod 'Firebase/Analytics'

target 'ferisTemplate' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ferisTemplateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ferisTemplate-tvOS' do
  # Pods for ferisTemplate-tvOS

  target 'ferisTemplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
